import { Game } from "../types";

export const BUILTIN_LUMIN_CATALOG: Omit<Game, "_search">[] = [
  { id: "lumin-1", name: "Slope", cover: "https://a.luminsdk.com/api/v1/icon/slope", url: "lumin:1", source: "lumin", luminId: "1", special: ["action", "arcade", "3d", "lumin"] },
  { id: "lumin-2", name: "Geometry Dash", cover: "https://a.luminsdk.com/api/v1/icon/geometry-dash", url: "lumin:2", source: "lumin", luminId: "2", special: ["action", "arcade", "music", "lumin"] },
  { id: "lumin-3", name: "Retro Bowl", cover: "https://a.luminsdk.com/api/v1/icon/retro-bowl", url: "lumin:3", source: "lumin", luminId: "3", special: ["sports", "retro", "arcade", "lumin"] },
  { id: "lumin-4", name: "Subway Surfers", cover: "https://a.luminsdk.com/api/v1/icon/subway-surfers", url: "lumin:4", source: "lumin", luminId: "4", special: ["action", "arcade", "runner", "lumin"] },
  { id: "lumin-5", name: "BitLife", cover: "https://a.luminsdk.com/api/v1/icon/bitlife", url: "lumin:5", source: "lumin", luminId: "5", special: ["simulation", "arcade", "lumin"] },
  { id: "lumin-6", name: "Smash Karts", cover: "https://a.luminsdk.com/api/v1/icon/smash-karts", url: "lumin:6", source: "lumin", luminId: "6", special: ["driving", "action", "multiplayer", "lumin"] },
  { id: "lumin-7", name: "Paper.io 2", cover: "https://a.luminsdk.com/api/v1/icon/paper-io-2", url: "lumin:7", source: "lumin", luminId: "7", special: ["action", "arcade", "io", "lumin"] },
  { id: "lumin-8", name: "Hole.io", cover: "https://a.luminsdk.com/api/v1/icon/hole-io", url: "lumin:8", source: "lumin", luminId: "8", special: ["action", "arcade", "io", "lumin"] },
  { id: "lumin-9", name: "Snow Rider 3D", cover: "https://a.luminsdk.com/api/v1/icon/snow-rider-3d", url: "lumin:9", source: "lumin", luminId: "9", special: ["driving", "action", "3d", "lumin"] },
  { id: "lumin-10", name: "Monkey Mart", cover: "https://a.luminsdk.com/api/v1/icon/monkey-mart", url: "lumin:10", source: "lumin", luminId: "10", special: ["management", "arcade", "lumin"] },
  { id: "lumin-11", name: "Drive Mad", cover: "https://a.luminsdk.com/api/v1/icon/drive-mad", url: "lumin:11", source: "lumin", luminId: "11", special: ["driving", "arcade", "physics", "lumin"] },
  { id: "lumin-12", name: "Moto X3M", cover: "https://a.luminsdk.com/api/v1/icon/moto-x3m", url: "lumin:12", source: "lumin", luminId: "12", special: ["driving", "action", "stunts", "lumin"] },
  { id: "lumin-13", name: "Basketball Stars", cover: "https://a.luminsdk.com/api/v1/icon/basketball-stars", url: "lumin:13", source: "lumin", luminId: "13", special: ["sports", "2-player", "arcade", "lumin"] },
  { id: "lumin-14", name: "Shell Shockers", cover: "https://a.luminsdk.com/api/v1/icon/shell-shockers", url: "lumin:14", source: "lumin", luminId: "14", special: ["shooting", "action", "fps", "lumin"] },
  { id: "lumin-15", name: "Crossy Road", cover: "https://a.luminsdk.com/api/v1/icon/crossy-road", url: "lumin:15", source: "lumin", luminId: "15", special: ["action", "arcade", "retro", "lumin"] },
  { id: "lumin-16", name: "OvO", cover: "https://a.luminsdk.com/api/v1/icon/ovo", url: "lumin:16", source: "lumin", luminId: "16", special: ["action", "parkour", "arcade", "lumin"] },
  { id: "lumin-17", name: "Flappy Bird", cover: "https://a.luminsdk.com/api/v1/icon/flappy-bird", url: "lumin:17", source: "lumin", luminId: "17", special: ["arcade", "retro", "lumin"] },
  { id: "lumin-18", name: "Cut the Rope", cover: "https://a.luminsdk.com/api/v1/icon/cut-the-rope", url: "lumin:18", source: "lumin", luminId: "18", special: ["puzzle", "arcade", "lumin"] },
  { id: "lumin-19", name: "Vex 7", cover: "https://a.luminsdk.com/api/v1/icon/vex-7", url: "lumin:19", source: "lumin", luminId: "19", special: ["action", "parkour", "arcade", "lumin"] },
  { id: "lumin-20", name: "Vex 6", cover: "https://a.luminsdk.com/api/v1/icon/vex-6", url: "lumin:20", source: "lumin", luminId: "20", special: ["action", "parkour", "arcade", "lumin"] },
  { id: "lumin-21", name: "Fireboy and Watergirl 1", cover: "https://a.luminsdk.com/api/v1/icon/fireboy-watergirl-1", url: "lumin:21", source: "lumin", luminId: "21", special: ["puzzle", "2-player", "arcade", "lumin"] },
  { id: "lumin-22", name: "Fireboy and Watergirl 2", cover: "https://a.luminsdk.com/api/v1/icon/fireboy-watergirl-2", url: "lumin:22", source: "lumin", luminId: "22", special: ["puzzle", "2-player", "arcade", "lumin"] },
  { id: "lumin-23", name: "Fireboy and Watergirl 3", cover: "https://a.luminsdk.com/api/v1/icon/fireboy-watergirl-3", url: "lumin:23", source: "lumin", luminId: "23", special: ["puzzle", "2-player", "arcade", "lumin"] },
  { id: "lumin-24", name: "Fireboy and Watergirl 4", cover: "https://a.luminsdk.com/api/v1/icon/fireboy-watergirl-4", url: "lumin:24", source: "lumin", luminId: "24", special: ["puzzle", "2-player", "arcade", "lumin"] },
  { id: "lumin-25", name: "Fireboy and Watergirl 5", cover: "https://a.luminsdk.com/api/v1/icon/fireboy-watergirl-5", url: "lumin:25", source: "lumin", luminId: "25", special: ["puzzle", "2-player", "arcade", "lumin"] },
  { id: "lumin-26", name: "Fireboy and Watergirl 6", cover: "https://a.luminsdk.com/api/v1/icon/fireboy-watergirl-6", url: "lumin:26", source: "lumin", luminId: "26", special: ["puzzle", "2-player", "arcade", "lumin"] },
  { id: "lumin-27", name: "Cookie Clicker", cover: "https://a.luminsdk.com/api/v1/icon/cookie-clicker", url: "lumin:27", source: "lumin", luminId: "27", special: ["arcade", "idle", "lumin"] },
  { id: "lumin-28", name: "Tunnel Rush", cover: "https://a.luminsdk.com/api/v1/icon/tunnel-rush", url: "lumin:28", source: "lumin", luminId: "28", special: ["action", "arcade", "3d", "lumin"] },
  { id: "lumin-29", name: "Rooftop Snipers", cover: "https://a.luminsdk.com/api/v1/icon/rooftop-snipers", url: "lumin:29", source: "lumin", luminId: "29", special: ["action", "shooting", "2-player", "lumin"] },
  { id: "lumin-30", name: "Eggy Car", cover: "https://a.luminsdk.com/api/v1/icon/eggy-car", url: "lumin:30", source: "lumin", luminId: "30", special: ["driving", "arcade", "physics", "lumin"] },
  { id: "lumin-31", name: "Stickman Hook", cover: "https://a.luminsdk.com/api/v1/icon/stickman-hook", url: "lumin:31", source: "lumin", luminId: "31", special: ["action", "arcade", "physics", "lumin"] },
  { id: "lumin-32", name: "Penalty Shooters 2", cover: "https://a.luminsdk.com/api/v1/icon/penalty-shooters-2", url: "lumin:32", source: "lumin", luminId: "32", special: ["sports", "arcade", "lumin"] },
  { id: "lumin-33", name: "Drift Hunters", cover: "https://a.luminsdk.com/api/v1/icon/drift-hunters", url: "lumin:33", source: "lumin", luminId: "33", special: ["driving", "3d", "drifting", "lumin"] },
  { id: "lumin-34", name: "Idle Breakout", cover: "https://a.luminsdk.com/api/v1/icon/idle-breakout", url: "lumin:34", source: "lumin", luminId: "34", special: ["arcade", "idle", "puzzle", "lumin"] },
  { id: "lumin-35", name: "Tomb of the Mask", cover: "https://a.luminsdk.com/api/v1/icon/tomb-of-the-mask", url: "lumin:35", source: "lumin", luminId: "35", special: ["action", "arcade", "retro", "lumin"] },
  { id: "lumin-36", name: "Tiny Fishing", cover: "https://a.luminsdk.com/api/v1/icon/tiny-fishing", url: "lumin:36", source: "lumin", luminId: "36", special: ["arcade", "casual", "lumin"] },
  { id: "lumin-37", name: "Crazy Cars", cover: "https://a.luminsdk.com/api/v1/icon/crazy-cars", url: "lumin:37", source: "lumin", luminId: "37", special: ["driving", "arcade", "stunts", "lumin"] },
  { id: "lumin-38", name: "Dreadhead Parkour", cover: "https://a.luminsdk.com/api/v1/icon/dreadhead-parkour", url: "lumin:38", source: "lumin", luminId: "38", special: ["action", "parkour", "arcade", "lumin"] },
  { id: "lumin-39", name: "Boxing Random", cover: "https://a.luminsdk.com/api/v1/icon/boxing-random", url: "lumin:39", source: "lumin", luminId: "39", special: ["sports", "2-player", "arcade", "lumin"] },
  { id: "lumin-40", name: "Soccer Random", cover: "https://a.luminsdk.com/api/v1/icon/soccer-random", url: "lumin:40", source: "lumin", luminId: "40", special: ["sports", "2-player", "arcade", "lumin"] },
  { id: "lumin-41", name: "Basket Random", cover: "https://a.luminsdk.com/api/v1/icon/basket-random", url: "lumin:41", source: "lumin", luminId: "41", special: ["sports", "2-player", "arcade", "lumin"] },
  { id: "lumin-42", name: "Volley Random", cover: "https://a.luminsdk.com/api/v1/icon/volley-random", url: "lumin:42", source: "lumin", luminId: "42", special: ["sports", "2-player", "arcade", "lumin"] },
  { id: "lumin-43", name: "2048", cover: "https://a.luminsdk.com/api/v1/icon/2048", url: "lumin:43", source: "lumin", luminId: "43", special: ["puzzle", "arcade", "lumin"] },
  { id: "lumin-44", name: "Wordle", cover: "https://a.luminsdk.com/api/v1/icon/wordle", url: "lumin:44", source: "lumin", luminId: "44", special: ["puzzle", "word", "lumin"] },
  { id: "lumin-45", name: "Chess", cover: "https://a.luminsdk.com/api/v1/icon/chess", url: "lumin:45", source: "lumin", luminId: "45", special: ["puzzle", "strategy", "2-player", "lumin"] },
  { id: "lumin-46", name: "Checkers", cover: "https://a.luminsdk.com/api/v1/icon/checkers", url: "lumin:46", source: "lumin", luminId: "46", special: ["puzzle", "strategy", "2-player", "lumin"] },
  { id: "lumin-47", name: "Getaway Shootout", cover: "https://a.luminsdk.com/api/v1/icon/getaway-shootout", url: "lumin:47", source: "lumin", luminId: "47", special: ["action", "shooting", "2-player", "lumin"] },
  { id: "lumin-48", name: "House of Hazards", cover: "https://a.luminsdk.com/api/v1/icon/house-of-hazards", url: "lumin:48", source: "lumin", luminId: "48", special: ["action", "2-player", "arcade", "lumin"] },
  { id: "lumin-49", name: "Monster Tracks", cover: "https://a.luminsdk.com/api/v1/icon/monster-tracks", url: "lumin:49", source: "lumin", luminId: "49", special: ["driving", "physics", "arcade", "lumin"] },
  { id: "lumin-50", name: "Crossy Road Space", cover: "https://a.luminsdk.com/api/v1/icon/crossy-road-space", url: "lumin:50", source: "lumin", luminId: "50", special: ["action", "arcade", "lumin"] },
  { id: "lumin-51", name: "Pac-Man 3D", cover: "https://a.luminsdk.com/api/v1/icon/pacman-3d", url: "lumin:51", source: "lumin", luminId: "51", special: ["retro", "arcade", "3d", "lumin"] },
  { id: "lumin-52", name: "Super Mario World", cover: "https://a.luminsdk.com/api/v1/icon/super-mario-world", url: "lumin:52", source: "lumin", luminId: "52", special: ["retro", "arcade", "lumin"] },
  { id: "lumin-53", name: "Sonic the Hedgehog", cover: "https://a.luminsdk.com/api/v1/icon/sonic-hedgehog", url: "lumin:53", source: "lumin", luminId: "53", special: ["retro", "arcade", "action", "lumin"] },
  { id: "lumin-54", name: "Tetris DX", cover: "https://a.luminsdk.com/api/v1/icon/tetris-dx", url: "lumin:54", source: "lumin", luminId: "54", special: ["puzzle", "retro", "arcade", "lumin"] },
  { id: "lumin-55", name: "Space Invaders", cover: "https://a.luminsdk.com/api/v1/icon/space-invaders", url: "lumin:55", source: "lumin", luminId: "55", special: ["shooting", "retro", "arcade", "lumin"] },
  { id: "lumin-56", name: "Friday Night Funkin' Original", cover: "https://a.luminsdk.com/api/v1/icon/fnf-original", url: "lumin:56", source: "lumin", luminId: "56", special: ["fnf", "music", "arcade", "lumin"] },
  { id: "lumin-57", name: "FNF VS Impostor V4", cover: "https://a.luminsdk.com/api/v1/icon/fnf-impostor-v4", url: "lumin:57", source: "lumin", luminId: "57", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-58", name: "FNF VS Sonic.EXE", cover: "https://a.luminsdk.com/api/v1/icon/fnf-sonic-exe", url: "lumin:58", source: "lumin", luminId: "58", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-59", name: "FNF VS Huggy Wuggy", cover: "https://a.luminsdk.com/api/v1/icon/fnf-huggy-wuggy", url: "lumin:59", source: "lumin", luminId: "59", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-60", name: "FNF VS Garcello", cover: "https://a.luminsdk.com/api/v1/icon/fnf-garcello", url: "lumin:60", source: "lumin", luminId: "60", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-61", name: "FNF VS Whitty Full Week", cover: "https://a.luminsdk.com/api/v1/icon/fnf-whitty", url: "lumin:61", source: "lumin", luminId: "61", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-62", name: "FNF VS Indie Cross", cover: "https://a.luminsdk.com/api/v1/icon/fnf-indie-cross", url: "lumin:62", source: "lumin", luminId: "62", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-63", name: "FNF VS Mario's Madness V2", cover: "https://a.luminsdk.com/api/v1/icon/fnf-marios-madness-v2", url: "lumin:63", source: "lumin", luminId: "63", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-64", name: "FNF VS Rainbow Friends", cover: "https://a.luminsdk.com/api/v1/icon/fnf-rainbow-friends", url: "lumin:64", source: "lumin", luminId: "64", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-65", name: "FNF VS Doors", cover: "https://a.luminsdk.com/api/v1/icon/fnf-doors", url: "lumin:65", source: "lumin", luminId: "65", special: ["fnf", "fnf-mod", "music", "lumin"] },
  { id: "lumin-66", name: "Stick War Legacy", cover: "https://a.luminsdk.com/api/v1/icon/stick-war-legacy", url: "lumin:66", source: "lumin", luminId: "66", special: ["action", "strategy", "arcade", "lumin"] },
  { id: "lumin-67", name: "Hill Climb Racing", cover: "https://a.luminsdk.com/api/v1/icon/hill-climb-racing", url: "lumin:67", source: "lumin", luminId: "67", special: ["driving", "physics", "arcade", "lumin"] },
  { id: "lumin-68", name: "Traffic Rider", cover: "https://a.luminsdk.com/api/v1/icon/traffic-rider", url: "lumin:68", source: "lumin", luminId: "68", special: ["driving", "action", "3d", "lumin"] },
  { id: "lumin-69", name: "Subway Surfers Space", cover: "https://a.luminsdk.com/api/v1/icon/subway-surfers-space", url: "lumin:69", source: "lumin", luminId: "69", special: ["action", "runner", "lumin"] },
  { id: "lumin-70", name: "Temple Run 2", cover: "https://a.luminsdk.com/api/v1/icon/temple-run-2", url: "lumin:70", source: "lumin", luminId: "70", special: ["action", "runner", "lumin"] },
];
